### ISSUE TITLE
Create bintray package

### ISSUE THREAD

**Issue by phisko** [AnotherFoxGuy/conan-ZZIPlib#1]
Hi,

I've been using your Ogre package on bintray, as it's the most reliable and easy to install Conan package I've found for Ogre. Thanks for that!

However, I recently wanted to make use of some of the Ogre 1.12 features (mainly the ImGui integration), and when attempting to switch to your 1.12.2/testing version, I noticed that your ZZIPlib package hasn't been uploaded to bintray.

Is there a particular reason why this is the case? If not, I'd really benefit from you adding this to bintray.

Again, thanks for packaging Ogre like you did :)

**Comment by phisko** [comment]
Additionally, FreeImage and GC are not on bintray either. I've built and exported these locally, but when I then try to install OGRE/1.12.2@anotherfoxguy/testing I get the following error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.WindowsSDK.targets(46,5): error MSB8036: The Windows SDK version 10.0.16299.0 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\NICOLAS-BUILD\.conan\data\freeimage\3.18.0\AnotherFoxGuy\stable\build\3fb49604f9c2f729b85ba3115852006824e72cab\FreeImage\Source\LibJXR\LibJXR.2017.vcxproj]
```

It would seem FreeImage depends on LibJXR, which was pre-built for a specific Windows SDK. Ideally, the JXR solution would be generated with CMake.

It seems this all implies a whole lot of work and I assume that's why these packages aren't on bintray yet. Let me know if there's any more information I can give you though, having someone testing with another configuration can sometimes help

**Comment by AnotherFoxGuy** [comment]
Sorry for the late reply, I've been busy with other projects

I've moved the dependencies required for OGRE from the ror-dependencies repository to a separate repository: https://bintray.com/anotherfoxguy/OGRE-dependencies
